// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class HighScoreImpl_Stub
    extends java.rmi.server.RemoteStub
    implements HighScore, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getHighestScore_0;
    private static java.lang.reflect.Method $method_setHighScore_1;
    
    static {
	try {
	    $method_getHighestScore_0 = HighScore.class.getMethod("getHighestScore", new java.lang.Class[] {});
	    $method_setHighScore_1 = HighScore.class.getMethod("setHighScore", new java.lang.Class[] {java.lang.String.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public HighScoreImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getHighestScore()
    public int getHighestScore()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getHighestScore_0, null, -675361037744627124L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setHighScore(String, int)
    public void setHighScore(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setHighScore_1, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, -8995401085816032287L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
